
[build]
target = "src/player.html"

[watch]
watch = [
  "./src/trailer/src.js",
  "./src/trailer/InteractiveVideo.js",
  "./src/trailer/VideoPlayer.js",
  "./src/trailer/ShaderBehavior.js",
  "./src/trailer/game1/module.js",
  "./src/trailer/game1/SpellCursorBehaviors.js",
  "./src/trailer/game1/SpellCursor.js",
  "./src/trailer/playgraph.js",
  "./src/trailer/player.html",
  "./src/trailer/main",
  "./src/trailer/DistortionShaderBehavior.js"
]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = true

[clean]
paths = ["./dist"]

# [[hooks]]
# stage = "pre_build"
# command = "./build.sh"

# [[hooks]]
# stage = "build"
# command = "./build.sh"

# [[hooks]]
# stage = "post_build"
# command = "sh"
# command_arguments = ["-c", "./build.sh"]



