[build]
target = "./public/player.html"

[watch]
watch = [
  "./src/trailer/src.js",
  "./src/trailer/InteractiveVideo.js",
  "./src/trailer/VideoPlayer.js",
  "./src/trailer/ShaderBehavior.js",
  "./src/trailer/SpellCursorBehaviors.js",
  "./src/trailer/playgraph.js",
  "./src/trailer/player.html",
  "./src/trailer/main",
]
ignore = ["./src-tauri", "./public"]

[serve]
address = "127.0.0.1"
port = 1420
open = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "./build.sh"]
